.AM
.de BL
.IP \(bu 2
..
.TL
Informations sheet
.AU
Se\*[']bastien Baudray
.AI
Groupe 18
.SH
Application pile used

.RS
.BL
Elixir as the main language
.BL
Phoenix as the web framework
.BL
PostgreSQL as the database
.BL
AWS EC2 for hosting
.BL
Docker as the container engine
.BL
Terraform as the IAC tool
.RE
.SH 
Version control sources URL

.PP
https://github.com/ferrandine/api-p
.SH 
Deployed project URL

.PP
http://ec2-35-180-118-48.eu-west-3.compute.amazonaws.com
