version: '3.7'

services:
  db:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eazip_dev
volumes:
  dbdata:
